<template>
  <section class="page">
    <div class="page-header"><div><h1>AI 分析记录</h1><p>只展示用户手动发起的第三方 AI 调用；页面查询不会调用模型。</p></div><el-button :loading="loading" @click="load">刷新</el-button></div>
    <el-alert type="info" :closable="false" show-icon title="每条记录保留模型、提示词版本、输入快照校验值、结果与失败原因；不会修改系统评分或交易纪律。" />
    <el-card shadow="never" class="filters"><el-form inline><el-form-item label="标的"><el-input v-model="ticker" clearable placeholder="NVDA" @change="search" /></el-form-item><el-form-item label="来源"><el-select v-model="scope" clearable placeholder="全部" style="width:180px" @change="search"><el-option label="标的评估" value="ticker_evaluation" /><el-option label="小盘候选详情" value="candidate_detail" /><el-option label="监控标的详情" value="watch_target_detail" /><el-option label="SEC 公告" value="sec_filing" /></el-select></el-form-item><el-button @click="search">查询</el-button></el-form></el-card>
    <el-table :data="rows" v-loading="loading" border empty-text="暂无 AI 分析记录" @row-click="select"><el-table-column prop="ticker" label="标的" width="100" fixed="left" /><el-table-column prop="company_name" label="公司 / 基金" min-width="180" show-overflow-tooltip /><el-table-column label="来源" width="145"><template #default="{ row }">{{ scopeLabel(row.scope) }}</template></el-table-column><el-table-column label="SEC 原文" width="100"><template #default="{ row }"><el-link v-if="row.source_url" :href="row.source_url" target="_blank" type="primary" @click.stop>原文</el-link><span v-else>-</span></template></el-table-column><el-table-column prop="provider_name" label="供应商" width="130" /><el-table-column prop="model" label="模型" width="150" /><el-table-column prop="template_name" label="模板" width="150"><template #default="{ row }">{{ row.template_name || '历史模板' }}</template></el-table-column><el-table-column prop="status" label="状态" width="100"><template #default="{ row }"><el-tag :type="statusTagType(row.status)" effect="plain">{{ statusLabel(row.status) }}</el-tag></template></el-table-column><el-table-column label="耗时" width="100" align="right"><template #default="{ row }">{{ duration(row.duration_ms) }}</template></el-table-column><el-table-column prop="requested_at" label="请求时间" width="175"><template #default="{ row }">{{ formatDate(row.requested_at) }}</template></el-table-column><el-table-column label="操作" width="80" fixed="right"><template #default="{ row }"><el-button link type="primary" @click.stop="select(row)">查看</el-button></template></el-table-column></el-table>
    <el-pagination v-model:current-page="page" :total="total" :page-size="pageSize" layout="total, prev, pager, next" class="pagination" @current-change="load" />
    <el-drawer v-model="drawer" :title="selected ? `${selected.ticker} · AI 研判` : 'AI 研判'" size="86vw"><template v-if="selected"><el-descriptions :column="2" border size="small"><el-descriptions-item label="来源">{{ scopeLabel(selected.scope) }}</el-descriptions-item><el-descriptions-item label="模型">{{ selected.provider_name }} · {{ selected.model }}</el-descriptions-item><el-descriptions-item label="模板">{{ selected.template_name || '历史模板' }}</el-descriptions-item><el-descriptions-item label="状态"><el-tag :type="selected.status === 'success' ? 'success' : 'danger'" effect="plain">{{ selected.status === 'success' ? '成功' : '失败' }}</el-tag></el-descriptions-item><el-descriptions-item label="SEC 原文" :span="2"><el-link v-if="selected.source_url" :href="selected.source_url" target="_blank" type="primary">{{ selected.source_url }}</el-link><span v-else>-</span></el-descriptions-item><el-descriptions-item label="耗时">{{ duration(selected.duration_ms) }}</el-descriptions-item><el-descriptions-item label="提示词版本">{{ selected.prompt_version }}</el-descriptions-item><el-descriptions-item label="结构版本">{{ selected.schema_version || '历史自由文本' }}</el-descriptions-item><el-descriptions-item label="请求次数">{{ selected.request_attempts || 0 }}</el-descriptions-item><el-descriptions-item label="结果来源"><span v-if="selected.reused_from_id">复用 #{{ selected.reused_from_id }}</span><span v-else>{{ selected.response_mode || '-' }}</span></el-descriptions-item><el-descriptions-item label="输入校验" :span="2">{{ selected.input_sha256 }}</el-descriptions-item><el-descriptions-item label="请求时间" :span="2">{{ formatDate(selected.requested_at) }}</el-descriptions-item></el-descriptions><AIRequestPrompt :system-prompt="selected.system_prompt" :user-prompt="selected.user_prompt" /><el-alert v-if="selected.status === 'failed'" type="error" :closable="false" :title="aiErrorMessage(selected.error_message)" style="margin-top:16px" /><div v-else class="content"><AIAnalysisResult :result="selected.structured_result" :content="selected.content" /></div></template></el-drawer>
  </section>
</template>
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { apiClient } from '@/api/client'
import { ElMessage } from 'element-plus'
import AIRequestPrompt from '@/components/AIRequestPrompt.vue'
import AIAnalysisResult from '@/components/AIAnalysisResult.vue'
import type { AIAnalysisStructuredResult } from '@/api/types'
type Analysis = { id:number; ticker:string; company_name:string; scope:string; source_url?:string; provider_name:string; model:string; template_name?:string; status:string; duration_ms?:number; content:string; error_message?:string; prompt_version:string; system_prompt?:string; user_prompt?:string; input_sha256:string; requested_at:string; schema_version?:string; structured_result?:AIAnalysisStructuredResult; request_attempts?:number; response_mode?:string; reused_from_id?:number }
const rows = ref<Analysis[]>([]); const loading = ref(false); const ticker = ref(''); const scope = ref(''); const page = ref(1); const pageSize = 20; const total = ref(0); const selected = ref<Analysis | null>(null); const drawer = ref(false); let pollingTimer:number|undefined
const route = useRoute()
async function load(){ loading.value=true; try { const r=await apiClient.get('/ai/analyses',{params:{ticker:ticker.value.trim().toUpperCase()||undefined,scope:scope.value||undefined,page:page.value,page_size:pageSize}}); rows.value=r.data.data.items||[];total.value=r.data.data.total||0;if(rows.value.some((item)=>item.status==='queued'||item.status==='running'))schedulePoll()}catch(e:any){ElMessage.error(e?.response?.data?.message||'加载 AI 分析记录失败')}finally{loading.value=false} }
function schedulePoll(){if(pollingTimer!==undefined)return;pollingTimer=window.setTimeout(()=>{pollingTimer=undefined;void load()},2000)}; function search(){page.value=1;void load()}; function select(row:Analysis){selected.value=row;drawer.value=true}; function formatDate(v?:string){return v?new Date(v).toLocaleString('zh-CN',{hour12:false,timeZone:'Asia/Shanghai'}):'-'}; function duration(v?:number){const value=Number(v);return Number.isFinite(value)&&value>0 ? (value<1000 ? `${value} ms` : `${(value/1000).toFixed(2)} s`) : '-'}; function statusLabel(v:string){return ({success:'成功',failed:'失败',queued:'排队中',running:'处理中'} as Record<string,string>)[v]||v}; function statusTagType(v:string){return v==='success'?'success':v==='failed'?'danger':'warning'}; function aiErrorMessage(v?:string){const error=v||'';if(/deadline exceeded|client\.timeout|context cancellation|timeout/i.test(error))return 'AI 提供商响应超时；可在“系统配置 → AI 分析”将该模型超时提高至 120–300 秒后手动重试。';if(/returned no analysis content|未输出分析正文/i.test(error))return '模型没有输出最终分析正文。已优化兼容推理模型；请重新手动提交一次任务。';return error||'AI 调用失败'}; function scopeLabel(v:string){return ({ticker_evaluation:'标的评估',candidate_detail:'小盘候选详情',watch_target_detail:'监控标的详情',sec_filing:'SEC 公告'} as Record<string,string>)[v]||v}
onMounted(()=>{ticker.value=typeof route.query.ticker==='string'?route.query.ticker:'';scope.value=typeof route.query.scope==='string'?route.query.scope:'';void load()});onUnmounted(()=>{if(pollingTimer!==undefined)window.clearTimeout(pollingTimer)})
</script>
<style scoped>.filters{margin:16px 0}.pagination{margin-top:16px;justify-content:flex-end}.content{padding:16px;margin-top:16px;background:var(--el-fill-color-light);border-radius:4px}</style>
