<template>
  <section class="page">
    <div class="page-header"><div><h1>AI 分析记录</h1><p>只展示用户手动发起的第三方 AI 调用；支持按状态筛选和同标的双版本比较。</p></div><el-button :loading="loading" @click="load">刷新</el-button></div>
    <el-alert type="info" :closable="false" show-icon title="每条记录保留模型、提示词版本、输入校验、结果与失败原因；不会修改系统评分或交易纪律。" />
    <el-card shadow="never" class="filters"><el-form inline><el-form-item label="标的"><el-input v-model="ticker" clearable placeholder="NVDA" @change="search" /></el-form-item><el-form-item label="来源"><el-select fit-input-width v-model="scope" clearable placeholder="全部" style="width:180px" @change="search"><el-option label="标的评估" value="ticker_evaluation" /><el-option label="小盘候选详情" value="candidate_detail" /><el-option label="监控标的详情" value="watch_target_detail" /><el-option label="SEC 公告" value="sec_filing" /></el-select></el-form-item><el-form-item label="状态"><el-select fit-input-width v-model="status" clearable placeholder="全部" style="width:120px" @change="search"><el-option label="成功" value="success" /><el-option label="失败" value="failed" /><el-option label="处理中" value="running" /></el-select></el-form-item><el-button @click="search">查询</el-button><el-button :disabled="comparisonRows.length !== 2" type="primary" plain @click="comparisonVisible=true">比较所选版本</el-button></el-form></el-card>
    <el-table :data="rows" v-loading="loading" border empty-text="暂无 AI 分析记录" @row-click="select" @selection-change="handleComparisonSelection"><el-table-column type="selection" width="42" :selectable="comparisonSelectable" fixed="left" /><el-table-column prop="ticker" label="标的" width="100" fixed="left"><template #default="{ row }"><el-link type="primary" @click.stop="openWorkspace(row)">{{ row.ticker }}</el-link></template></el-table-column><el-table-column prop="company_name" label="公司 / 基金" min-width="180" show-overflow-tooltip /><el-table-column label="来源" width="145"><template #default="{ row }"><el-link v-if="isLinkedSECFiling(row)" :href="row.source_url" target="_blank" type="primary" @click.stop>{{ scopeLabel(row.scope) }}</el-link><span v-else>{{ scopeLabel(row.scope) }}</span></template></el-table-column><el-table-column prop="provider_name" label="供应商" width="130" /><el-table-column prop="model" label="模型" width="150" /><el-table-column prop="template_name" label="模板" width="150"><template #default="{ row }">{{ row.template_name || '历史模板' }}</template></el-table-column><el-table-column prop="status" label="状态" width="100"><template #default="{ row }"><el-tag :type="statusTagType(row.status)" effect="plain">{{ statusLabel(row.status) }}</el-tag></template></el-table-column><el-table-column label="失败原因" min-width="170" show-overflow-tooltip><template #default="{ row }">{{ row.status === 'failed' ? aiErrorMessage(row.error_message) : '-' }}</template></el-table-column><el-table-column label="耗时" width="100" align="right"><template #default="{ row }">{{ duration(row.duration_ms) }}</template></el-table-column><el-table-column prop="requested_at" label="请求时间" width="175"><template #default="{ row }">{{ formatDate(row.requested_at) }}</template></el-table-column><el-table-column label="操作" width="80" fixed="right"><template #default="{ row }"><el-button link type="primary" @click.stop="select(row)">查看</el-button></template></el-table-column></el-table>
    <el-pagination v-model:current-page="page" :total="total" :page-size="pageSize" layout="total, prev, pager, next" class="pagination" @current-change="load" />
    <el-drawer v-model="drawer" :title="selected ? `${selected.ticker} · AI 研判` : 'AI 研判'" size="86vw"><template v-if="selected"><el-descriptions :column="2" border size="small"><el-descriptions-item label="来源">{{ scopeLabel(selected.scope) }}</el-descriptions-item><el-descriptions-item label="模型">{{ selected.provider_name }} · {{ selected.model }}</el-descriptions-item><el-descriptions-item label="模板">{{ selected.template_name || '历史模板' }}</el-descriptions-item><el-descriptions-item label="状态"><el-tag :type="statusTagType(selected.status)" effect="plain">{{ statusLabel(selected.status) }}</el-tag></el-descriptions-item><el-descriptions-item label="耗时">{{ duration(selected.duration_ms) }}</el-descriptions-item><el-descriptions-item label="提示词版本">{{ selected.prompt_version }}</el-descriptions-item><el-descriptions-item label="结构版本">{{ selected.schema_version || '历史自由文本' }}</el-descriptions-item><el-descriptions-item label="请求次数">{{ selected.request_attempts || 0 }}</el-descriptions-item><el-descriptions-item label="输入校验" :span="2">{{ selected.input_sha256 }}</el-descriptions-item><el-descriptions-item label="请求时间" :span="2">{{ formatDate(selected.requested_at) }}</el-descriptions-item></el-descriptions><AIRequestPrompt :system-prompt="selected.system_prompt" :user-prompt="selected.user_prompt" /><el-alert v-if="selected.status === 'failed'" type="error" :closable="false" :title="aiErrorMessage(selected.error_message)" style="margin-top:16px" /><template v-else><el-alert v-if="selected.validation_warning" type="warning" :closable="false" show-icon title="模型输出未通过结构校验，系统已安全降级为证据不足。" :description="selected.validation_warning" style="margin-top:16px" /><div class="content"><AIAnalysisResult :result="selected.structured_result" :content="selected.content" /></div></template></template></el-drawer>
    <el-dialog v-model="comparisonVisible" title="AI 研判版本比较" width="min(1100px, 92vw)"><div class="compare-grid"><el-card v-for="item in comparisonRows" :key="item.id" shadow="never"><template #header><strong>{{ item.provider_name }} · {{ item.model }}</strong><small>{{ formatDate(item.requested_at) }}</small></template><el-descriptions :column="1" size="small" border><el-descriptions-item label="模板">{{ item.template_name || '历史模板' }}</el-descriptions-item><el-descriptions-item label="立场">{{ item.structured_result?.stance || '-' }}</el-descriptions-item><el-descriptions-item label="证据充分度">{{ item.structured_result?.evidence_sufficiency || '-' }}</el-descriptions-item><el-descriptions-item label="结论">{{ item.structured_result?.conclusion || item.error_message || '-' }}</el-descriptions-item><el-descriptions-item label="催化剂">{{ item.structured_result?.catalysts?.join('；') || '-' }}</el-descriptions-item><el-descriptions-item label="风险">{{ item.structured_result?.risk_notes?.join('；') || '-' }}</el-descriptions-item></el-descriptions></el-card></div></el-dialog>
  </section>
</template>
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { apiClient } from '@/api/client'
import { ElMessage } from 'element-plus'
import AIRequestPrompt from '@/components/AIRequestPrompt.vue'
import AIAnalysisResult from '@/components/AIAnalysisResult.vue'
import type { AIAnalysisStructuredResult } from '@/api/types'
type Analysis={id:number;ticker:string;company_name:string;scope:string;source_url?:string;provider_name:string;model:string;template_name?:string;status:string;duration_ms?:number;content:string;error_message?:string;validation_warning?:string;prompt_version:string;system_prompt?:string;user_prompt?:string;input_sha256:string;requested_at:string;schema_version?:string;structured_result?:AIAnalysisStructuredResult;request_attempts?:number}
const route=useRoute(),router=useRouter();const rows=ref<Analysis[]>([]),loading=ref(false),ticker=ref(''),scope=ref(''),status=ref(''),page=ref(1),total=ref(0),selected=ref<Analysis|null>(null),drawer=ref(false),comparisonRows=ref<Analysis[]>([]),comparisonVisible=ref(false);const pageSize=20;let pollingTimer:number|undefined
async function load(){loading.value=true;try{const r=await apiClient.get('/ai/analyses',{params:{ticker:ticker.value.trim().toUpperCase()||undefined,scope:scope.value||undefined,status:status.value||undefined,page:page.value,page_size:pageSize}});rows.value=r.data.data.items||[];total.value=r.data.data.total||0;if(rows.value.some(item=>item.status==='queued'||item.status==='running'))schedulePoll()}catch(e:any){ElMessage.error(e?.response?.data?.message||'加载 AI 分析记录失败')}finally{loading.value=false}}
function schedulePoll(){if(pollingTimer!==undefined)return;pollingTimer=window.setTimeout(()=>{pollingTimer=undefined;void load()},2000)}function search(){page.value=1;void load()}function select(row:Analysis){selected.value=row;drawer.value=true}function handleComparisonSelection(items:Analysis[]){comparisonRows.value=items.slice(-2)}function comparisonSelectable(row:Analysis){return comparisonRows.value.length<2||comparisonRows.value.some(item=>item.id===row.id)}function openWorkspace(row:Analysis){router.push({path:'/ticker-workspace',query:{ticker:row.ticker}})}
function formatDate(v?:string){return v?new Date(v).toLocaleString('zh-CN',{hour12:false,timeZone:'Asia/Shanghai'}):'-'}function duration(v?:number){const n=Number(v);return Number.isFinite(n)&&n>0?(n<1000?`${n} ms`:`${(n/1000).toFixed(2)} s`):'-'}function statusLabel(v:string){return({success:'成功',failed:'失败',queued:'排队中',running:'处理中'}as Record<string,string>)[v]||v}function statusTagType(v:string){return v==='success'?'success':v==='failed'?'danger':'warning'}function aiErrorMessage(v?:string){const e=v||'';if(/deadline exceeded|timeout/i.test(e))return'AI 提供商响应超时';if(/结构|unmarshal|evidence/i.test(e))return'模型输出未满足结构约束';return e||'AI 调用失败'}function scopeLabel(v:string){return({ticker_evaluation:'标的评估',candidate_detail:'小盘候选详情',watch_target_detail:'监控标的详情',sec_filing:'SEC 公告'}as Record<string,string>)[v]||v}function isLinkedSECFiling(row:Analysis){return row.scope==='sec_filing'&&/^https?:\/\//i.test((row.source_url||'').trim())}
onMounted(()=>{ticker.value=typeof route.query.ticker==='string'?route.query.ticker:'';scope.value=typeof route.query.scope==='string'?route.query.scope:'';status.value=typeof route.query.status==='string'?route.query.status:'';void load()});onUnmounted(()=>{if(pollingTimer!==undefined)window.clearTimeout(pollingTimer)})
</script>
<style scoped>.filters{margin:12px 0}.filters :deep(.el-card__body){padding:10px 12px}.filters :deep(.el-form-item){margin-bottom:0}.pagination{margin-top:12px;justify-content:flex-end}.content{padding:12px;margin-top:12px;background:var(--el-fill-color-light);border-radius:4px}.compare-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.compare-grid small{display:block;color:var(--el-text-color-secondary);margin-top:4px}@media(max-width:760px){.compare-grid{grid-template-columns:1fr}}</style>
