<template>
  <section class="page"><div class="page-header"><div><h1>机构持仓</h1><p class="muted">Longbridge Terminal / SEC EDGAR 13F。13F 为滞后披露，需结合原文公告阅读。</p></div><el-button type="primary" :loading="syncing" @click="syncNow">同步最新 13F</el-button></div>
    <el-table :data="investorsWithUpcoming" v-loading="loading" border style="margin-top:16px" @row-click="open"><el-table-column prop="firm" label="机构" min-width="280" show-overflow-tooltip/><el-table-column prop="cik" label="CIK" width="125"/><el-table-column prop="report_date" label="报告期" width="125" sortable/><el-table-column prop="filing_date" label="实际提交日" width="125" sortable/><el-table-column prop="next_period" label="下一报告期" width="125" sortable/><el-table-column prop="due_date" label="最晚提交日" width="125" sortable/><el-table-column label="组合市值" width="160" align="right"><template #default="{row}">{{ money(row.total_value_usd) }}</template></el-table-column><el-table-column prop="total_holdings" label="持仓数" width="100" align="right"/><el-table-column label="13F 公告" width="100"><template #default="{row}"><el-link :href="row.source_url" target="_blank" type="primary">原文</el-link></template></el-table-column></el-table>
    <el-drawer v-model="visible" :title="detail?.filing?.firm || '机构详情'" size="80%"><template v-if="detail"><el-descriptions :column="4" border><el-descriptions-item label="报告期">{{ detail.filing.report_date }}</el-descriptions-item><el-descriptions-item label="提交日">{{ detail.filing.filing_date }}</el-descriptions-item><el-descriptions-item label="组合市值">{{ money(detail.filing.total_value_usd) }}</el-descriptions-item><el-descriptions-item label="13F"><el-link :href="detail.filing.source_url" target="_blank">查看公告原文</el-link></el-descriptions-item></el-descriptions><h3>最新披露持仓</h3><el-input v-model="holdingQuery" clearable placeholder="搜索代码、证券名称或 CUSIP，例如 NVDA" style="width:320px;margin-bottom:12px"/><el-table :data="filteredHoldings" border max-height="480"><el-table-column label="标的" width="95" sortable :sort-method="(a:any,b:any)=>tickerFor(a).localeCompare(tickerFor(b))"><template #default="{row}">{{ tickerFor(row) || '-' }}</template></el-table-column><el-table-column prop="issuer" label="证券" min-width="230" sortable/><el-table-column prop="title_of_class" label="类别" width="90" sortable/><el-table-column prop="cusip" label="CUSIP" width="110" sortable/><el-table-column prop="shares" label="股数" width="140" align="right" sortable/><el-table-column prop="value_usd" label="市值" width="160" align="right" sortable><template #default="{row}">{{ money(row.value_usd) }}</template></el-table-column><el-table-column prop="weight_pct" label="组合权重" width="110" align="right" sortable><template #default="{row}">{{ row.weight_pct.toFixed(2) }}%</template></el-table-column></el-table><h3>历次披露</h3><el-table :data="detail.history" border><el-table-column prop="report_date" label="报告期"/><el-table-column prop="filing_date" label="提交日"/><el-table-column label="市值"><template #default="{row}">{{ money(row.total_value_usd) }}</template></el-table-column><el-table-column label="公告"><template #default="{row}"><el-link :href="row.source_url" target="_blank">13F 原文</el-link></template></el-table-column></el-table></template></el-drawer>
  </section>
</template>
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { apiClient } from '@/api/client'
const investors = ref<any[]>([])
const loading = ref(false)
const syncing = ref(false)
const visible = ref(false)
const detail = ref<any>(null)
const holdingQuery = ref('')
const cusipTickers: Record<string, string> = { '67066G104':'NVDA', '037833100':'AAPL', '594918104':'MSFT', '023135106':'AMZN', '02079K305':'GOOGL', '02079K107':'GOOG', '11135F101':'AVGO' }
const tickerFor = (row:any) => cusipTickers[row.cusip] || ''
const upcomingFilings = computed(() => investors.value.map((row:any) => { const months:Record<string,number>={JAN:0,FEB:1,MAR:2,APR:3,MAY:4,JUN:5,JUL:6,AUG:7,SEP:8,OCT:9,NOV:10,DEC:11}; const parts=String(row.report_date).split('-'); const d=new Date(Number(parts[2]), months[parts[1]] ?? 0, Number(parts[0])); d.setMonth(d.getMonth()+3); const period=d.toISOString().slice(0,10); const due=new Date(d); due.setDate(due.getDate()+45); return { firm:row.firm, next_period:period, due_date:due.toISOString().slice(0,10), status:'预计披露窗口' } }))
const investorsWithUpcoming = computed(() => upcomingFilings.value.map((item:any) => ({ ...investors.value.find((row:any) => row.firm === item.firm), ...item, disclosure_status: item.status })))
const filteredHoldings = computed(() => { const q=holdingQuery.value.trim().toLowerCase(); const rows=detail.value?.holdings||[]; return q ? rows.filter((r:any)=>[tickerFor(r),r.issuer,r.cusip].some(v=>String(v||'').toLowerCase().includes(q))) : rows })
const money = (value: number) => `$${Number(value || 0).toLocaleString()}`
async function load() { loading.value = true; try { investors.value = (await apiClient.get('/institutional-filings')).data.data } catch { ElMessage.error('加载机构持仓失败') } finally { loading.value = false } }
async function syncNow() { syncing.value = true; try { const response = await apiClient.post('/institutional-filings/sync'); ElMessage.success(response.data.data.message); await load() } catch (error: any) { ElMessage.error(error?.response?.data?.message || '同步失败') } finally { syncing.value = false } }
async function open(row: any) { detail.value = (await apiClient.get(`/institutional-filings/${row.cik}`)).data.data; visible.value = true }
onMounted(load)
</script>
