<template>
  <section class="page">
    <div class="page-header"><div><h1>机构持仓</h1><p>标的视角用于披露期变化复核；未出现在最新批次仅标记“未续披露”，不直接推断已经清仓。机构视角展示 SEC 13F 组合。</p></div><el-button v-if="viewMode==='institution'" type="primary" :loading="syncing" @click="syncNow">同步最新 13F</el-button></div>
    <el-tabs v-model="viewMode" class="view-tabs">
      <el-tab-pane label="按标的看变化" name="ticker">
        <el-card shadow="never" class="query-card"><el-form inline @submit.prevent="loadTicker"><el-form-item label="Ticker"><el-input v-model="ticker" placeholder="NVDA" clearable @keyup.enter="loadTicker" /></el-form-item><el-button type="primary" :loading="tickerLoading" @click="loadTicker">查询本地持仓</el-button></el-form></el-card>
        <el-alert v-if="tickerMessage" type="info" :closable="false" class="gap" :title="tickerMessage" />
        <div v-if="tickerRows.length || fundRows.length" class="metric-strip gap"><div><span>最新披露批次</span><strong>{{ latestDate || '-' }}</strong></div><div><span>机构 / 基金</span><strong>{{ tickerRows.length }} / {{ fundRows.length }}</strong></div><div><span>新披露 / 未续披露</span><strong>{{ changeCounts.new }} / {{ changeCounts.closed }}</strong></div><div><span>增持 / 减持</span><strong>{{ changeCounts.increased }} / {{ changeCounts.decreased }}</strong></div></div>
        <el-card shadow="never" class="gap"><template #header><strong>机构股东季度变化</strong></template><el-table :data="tickerRows" v-loading="tickerLoading" size="small" border empty-text="暂无机构股东历史"><el-table-column prop="holder_name" label="机构" min-width="210" show-overflow-tooltip /><el-table-column prop="institution_type" label="类型" width="110" /><el-table-column label="最新比例" width="110" align="right"><template #default="{row}">{{ pct(row.percent_of_shares) }}</template></el-table-column><el-table-column label="上期比例" width="110" align="right"><template #default="{row}">{{ pct(row.previous) }}</template></el-table-column><el-table-column label="季度变化" width="120" align="right"><template #default="{row}"><span :class="deltaClass(row.delta)">{{ signedPct(row.delta) }}</span></template></el-table-column><el-table-column label="状态" width="95"><template #default="{row}"><el-tag :type="changeType(row.change)" effect="plain">{{ changeLabel(row.change) }}</el-tag></template></el-table-column><el-table-column prop="report_date" label="报告期" width="115" /><el-table-column label="来源" width="75"><template #default="{row}"><el-link v-if="row.source_url" :href="row.source_url" target="_blank" type="primary">原文</el-link></template></el-table-column></el-table></el-card>
        <el-card shadow="never" class="gap"><template #header><strong>基金 / ETF 组合权重变化</strong></template><el-table :data="fundRows" size="small" border empty-text="暂无基金持仓历史"><el-table-column prop="fund_symbol" label="代码" width="95" /><el-table-column prop="fund_name" label="基金" min-width="220" show-overflow-tooltip /><el-table-column label="最新权重" width="110" align="right"><template #default="{row}">{{ pct(row.position_ratio) }}</template></el-table-column><el-table-column label="上期权重" width="110" align="right"><template #default="{row}">{{ pct(row.previous) }}</template></el-table-column><el-table-column label="季度变化" width="120" align="right"><template #default="{row}"><span :class="deltaClass(row.delta)">{{ signedPct(row.delta) }}</span></template></el-table-column><el-table-column label="状态" width="95"><template #default="{row}"><el-tag :type="changeType(row.change)" effect="plain">{{ changeLabel(row.change) }}</el-tag></template></el-table-column><el-table-column prop="report_date" label="报告期" width="115" /></el-table></el-card>
      </el-tab-pane>
      <el-tab-pane label="按机构看 13F" name="institution">
        <el-table :data="investorsWithUpcoming" v-loading="loading" border @row-click="open"><el-table-column prop="firm" label="机构" min-width="280" show-overflow-tooltip/><el-table-column prop="cik" label="CIK" width="125"/><el-table-column prop="report_date" label="报告期" width="125" sortable/><el-table-column prop="filing_date" label="提交日" width="125" sortable/><el-table-column prop="due_date" label="下次截止" width="125"/><el-table-column label="组合市值" width="160" align="right"><template #default="{row}">{{ money(row.total_value_usd) }}</template></el-table-column><el-table-column prop="total_holdings" label="持仓数" width="100" align="right"/><el-table-column label="公告" width="80"><template #default="{row}"><el-link :href="row.source_url" target="_blank" type="primary">原文</el-link></template></el-table-column></el-table>
      </el-tab-pane>
    </el-tabs>
    <el-drawer v-model="visible" :title="detail?.filing?.firm || '机构详情'" size="80%"><template v-if="detail"><el-descriptions :column="3" border><el-descriptions-item label="报告期">{{ detail.filing.report_date }}</el-descriptions-item><el-descriptions-item label="提交日">{{ detail.filing.filing_date }}</el-descriptions-item><el-descriptions-item label="组合市值">{{ money(detail.filing.total_value_usd) }}</el-descriptions-item></el-descriptions><h3>最新披露持仓</h3><el-table :data="detail.holdings||[]" border max-height="520"><el-table-column prop="issuer" label="证券" min-width="230"/><el-table-column prop="cusip" label="CUSIP" width="110"/><el-table-column prop="shares" label="股数" width="140" align="right"/><el-table-column label="市值" width="160" align="right"><template #default="{row}">{{ money(row.value_usd) }}</template></el-table-column><el-table-column label="组合权重" width="110" align="right"><template #default="{row}">{{ pct(row.weight_pct) }}</template></el-table-column></el-table></template></el-drawer>
  </section>
</template>
<script setup lang="ts">
import { computed,onMounted,ref } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { apiClient } from '@/api/client'
const route=useRoute(),router=useRouter();const viewMode=ref('ticker'),ticker=ref(''),tickerLoading=ref(false),tickerMessage=ref(''),history=ref<any>({institutional_holders:[],fund_holders:[]}),investors=ref<any[]>([]),loading=ref(false),syncing=ref(false),visible=ref(false),detail=ref<any>(null)
const dates=(items:any[])=>[...new Set(items.map(x=>x.report_date).filter(Boolean))].sort().reverse();const latestDate=computed(()=>dates([...(history.value.institutional_holders||[]),...(history.value.fund_holders||[])])[0]||'')
function compare(items:any[],key:string,valueKey:string){const ds=dates(items),latest=ds[0],previous=ds[1],a=new Map(items.filter(x=>x.report_date===latest).map(x=>[String(x[key]),x])),b=new Map(items.filter(x=>x.report_date===previous).map(x=>[String(x[key]),x]));const result:any[]=[];a.forEach((row:any,id:string)=>{const old:any=b.get(id),current=Number(row[valueKey]),prior=old?Number(old[valueKey]):undefined,delta=old?current-Number(old[valueKey]):undefined;result.push({...row,previous:prior,delta,change:!old?'new':Number(delta)>0?'increased':Number(delta)<0?'decreased':'unchanged'})});b.forEach((row:any,id:string)=>{if(!a.has(id))result.push({...row,report_date:latest,previous:Number(row[valueKey]),[valueKey]:undefined,delta:-Number(row[valueKey]),change:'closed'})});return result.sort((x,y)=>Math.abs(y.delta||0)-Math.abs(x.delta||0))}
const tickerRows=computed(()=>compare(history.value.institutional_holders||[],'holder_name','percent_of_shares'));const fundRows=computed(()=>compare(history.value.fund_holders||[],'fund_symbol','position_ratio'));const changeCounts=computed(()=>[...tickerRows.value,...fundRows.value].reduce((a:any,x:any)=>(a[x.change]=(a[x.change]||0)+1,a),{new:0,closed:0,increased:0,decreased:0}))
async function loadTicker(){const s=ticker.value.trim().toUpperCase();if(!s){ElMessage.warning('请输入标的代码');return}ticker.value=s;tickerLoading.value=true;try{const r=await apiClient.get(`/discovery/institutional-holdings/${encodeURIComponent(s)}`);history.value=r.data.data||{institutional_holders:[],fund_holders:[]};tickerMessage.value=history.value.message||'';await router.replace({query:{ticker:s}})}catch(e:any){ElMessage.error(e?.response?.data?.message||'加载标的持仓失败')}finally{tickerLoading.value=false}}
const investorsWithUpcoming=computed(()=>investors.value.map((row:any)=>{const d=new Date(row.report_date);d.setMonth(d.getMonth()+3);const due=new Date(d);due.setDate(due.getDate()+45);return{...row,due_date:due.toISOString().slice(0,10)}}));async function load(){loading.value=true;try{investors.value=(await apiClient.get('/institutional-filings')).data.data}catch{ElMessage.error('加载机构持仓失败')}finally{loading.value=false}}async function syncNow(){syncing.value=true;try{const r=await apiClient.post('/institutional-filings/sync');ElMessage.success(r.data.data.message);await load()}finally{syncing.value=false}}async function open(row:any){detail.value=(await apiClient.get(`/institutional-filings/${row.cik}`)).data.data;visible.value=true}
function pct(v:any){return Number.isFinite(Number(v))?`${Number(v).toFixed(2)}%`:'-'}function signedPct(v:any){return Number.isFinite(Number(v))?`${Number(v)>=0?'+':''}${Number(v).toFixed(2)}pp`:'-'}function money(v:any){return `$${Number(v||0).toLocaleString()}`}function deltaClass(v:any){return Number(v)>0?'positive':Number(v)<0?'negative':''}function changeLabel(v:string){return({new:'新披露',closed:'未续披露',increased:'增持',decreased:'减持',unchanged:'持平'}as any)[v]||v}function changeType(v:string){return v==='new'||v==='increased'?'success':v==='closed'||v==='decreased'?'warning':'info'}
onMounted(()=>{ticker.value=typeof route.query.ticker==='string'?route.query.ticker.toUpperCase():'';if(ticker.value)void loadTicker();void load()})
</script>
<style scoped>.view-tabs{margin-top:8px}.query-card :deep(.el-card__body){padding:10px 12px}.query-card :deep(.el-form-item){margin-bottom:0}.gap{margin-top:12px}.metric-strip{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid var(--el-border-color-light);border-radius:6px}.metric-strip div{padding:12px 15px;border-right:1px solid var(--el-border-color-lighter)}.metric-strip div:last-child{border:0}.metric-strip span{display:block;color:var(--el-text-color-secondary);font-size:12px}.metric-strip strong{display:block;font-size:22px;margin-top:4px}.positive{color:var(--el-color-success)}.negative{color:var(--el-color-danger)}</style>
