import type {
  CandidateDetail,
  CandidateHealth,
  CandidateNotificationPreview,
  CandidateNotificationSendInput,
  CandidateNotificationSendResult,
  CandidateReport,
  CandidateScore,
  CandidateSelectionCriteria,
  CandidateSummary,
  DiscoveryWorkflowResult,
} from './types'

// Compile-time contract guard for discovery candidate summary API payloads.
const candidate: CandidateScore = {
  id: 1,
  batch_id: 'batch',
  security_id: 1,
  ticker: 'ACME',
  market_cap_usd: 240_000_000,
  grade: 'A',
  eligible_a: true,
  eligible_b: true,
  total_score: 88,
  revenue_growth_score: 30,
  cash_runway_score: 20,
  insider_score: 20,
  gross_margin_score: 8,
  dilution_risk_score: 10,
  sector_score: 8,
  revenue_growth_pct: 55,
  cash_runway_months: 18,
  recent_qualified_insider: true,
  active_blocks_a: false,
  active_blocks_b: false,
  reason_code: 'qualified',
  scoring_version: 'v1',
	scoring_rubric_sha256: 'abc123',
  created_at: '2026-06-29T00:00:00Z',
}

export const candidateSummaryTypecheck: CandidateSummary = {
  batch_id: 'batch',
  total_a: 1,
  total_b: 0,
  items_a: [candidate],
  items_b: [],
  event_notes: { ACME: '新增入选' },
  message: '小盘股研究候选摘要',
}

export const candidateSelectionCriteriaTypecheck: CandidateSelectionCriteria = {
  scoring_version: 'small-cap-discovery-score-v1',
	scoring_rubric: {
	  version: 'small-cap-discovery-score-v1',
	  name: '小盘候选确定性基本面评分卡',
	  formula: '总分 = 六项评分之和',
	  max_score: 100,
	  dimensions: [{ key: 'revenue_growth', label: '收入增长', max_points: 30, weight_pct: 30, evidence: 'SEC 财务事实', rules: [{ condition: '增长率 ≥ 40%', points: 30 }] }],
	  grade_rule_note: '等级由独立闸门决定',
	  disclaimer: '不是涨跌概率或投资建议',
	  content_sha256: 'abc123',
	},
  market_cap_min_usd: 30_000_000,
  a_market_cap_max_exclusive_usd: 500_000_000,
  b_market_cap_max_exclusive_usd: 1_000_000_000,
  a_revenue_growth_min_pct: 40,
  b_revenue_growth_min_pct: 20,
  a_revenue_growth_min_exclusive_pct: 40,
  b_revenue_growth_min_exclusive_pct: 20,
  a_runway_min_months: 12,
  insider_lookback_days: 180,
  b_min_sector_score: 7,
  allowed_exchanges: ['Nasdaq', 'NYSE', 'NYSE American'],
  max_price_age_trading_days: 3,
  minimum_price_usd: 1,
  blocked_adv_usd: 100_000,
  tradable_adv_usd: 500_000,
  minimum_history_days: 15,
  revenue_growth_selection: '优先最新可比季度收入同比；季度不可用时回退年度同比',
  qualified_insider_requirement: '近 180 日 CEO、CFO 或创始人的合格 Form 4 公开市场买入',
  active_capital_risk_requirement: 'A级不允许 A/B 阻断；B级不允许 B 阻断',
}

export const candidateNotificationPreviewTypecheck: CandidateNotificationPreview = {
  enabled: true,
  suppressed_reason: '',
  settings: {
    enabled: true,
    notify_a: true,
    notify_b: false,
    send_time: '09:30',
    max_per_grade: 5,
    actionable_only: true,
    min_review_priority_score: 0,
  },
  summary: candidateSummaryTypecheck,
}

export const candidateNotificationSendResultTypecheck: CandidateNotificationSendResult = {
  preview: candidateNotificationPreviewTypecheck,
  batch: {
    id: 1,
    sync_run_id: 0,
    source: 'candidate',
    trigger: 'manual',
    channel: 'telegram',
    target: 'chat',
    status: 'sent',
    item_count: 1,
    sent_count: 1,
    suppressed_count: 0,
    failed_count: 0,
    retry_count: 0,
    created_at: '2026-06-30T00:00:00Z',
  },
}

export const candidateNotificationSendInputTypecheck: CandidateNotificationSendInput = {
  confirm: true,
  force: false,
}

export const candidateDetailTypecheck: CandidateDetail = {
  batch_id: 'batch',
  security: { id: 1, cik: '0001', company_name: 'Acme', sic: 1000, catalog_status: 'published' },
	company_profile: { ticker: 'ACME', company_name: 'Acme', cik: '0001', sic: 1000, business_summary: 'SEC 行业概览。', summary_source: 'SEC submissions / SIC（赛道回退）', status: 'partial' },
	analyst_rating: { history: [], message: '尚未同步分析师共识' },
	market_research: { eps_forecast: { history: [], message: '尚未同步 EPS 预期' }, eps_revision: { status: 'insufficient', direction: 'unknown', compared_snapshots: 0, message: '样本不足' }, earnings_surprise: { status: 'unavailable', message: '尚缺时点一致数据' }, anomalies: [], institutional_holders: [], fund_holders: [] },
  score: candidate,
	scoring_rubric: candidateSelectionCriteriaTypecheck.scoring_rubric,
  score_history: [],
  signal_events: [],
  insiders: [],
  capital_risks: [],
  capital_risk_summary: { total_events: 0, active_events: 0, recent_inactive_events: 0, historical_inactive_count: 0 },
  sector: { sic: 1000, category: '未分类赛道', score: 8, label: '优秀赛道', rationale: '基于 SIC 1000。' },
  business_model: { model: 'not_applicable', revenue_repeatable_confirmed: false, revenue_score_cap: 30, revenue_score_cap_reason: '', requires_review: false, reason: '', source_url: '', operator: '' },
  valuation: { status: 'partial', reasons: ['ttm_revenue_unavailable'], price_trade_date: '', financial_period_end: '', share_instant: '' },
	valuation_research: { history: [], message: '尚未同步 Longbridge 估值研究' },
  fair_value: { status: 'insufficient', currency: 'USD', analyst_count: 0, metric_scenarios: [], methodology: '', message: '缺少输入' },
  investability: { status: 'tradable', reasons: [], sample_days: 21, average_dollar_volume_usd: 1_000_000, suggested_max_daily_notional_usd: 50_000, max_adv_participation_pct: 5, spread_evidence_status: 'not_available_eod' },
  dilution_trend: { status: 'stable', reasons: [], share_change_pct: 2.5, latest_shares: 10_250_000, prior_shares: 10_000_000, latest_instant: '2026-06-30', prior_instant: '2025-06-30', observation_days: 365 },
  research_versions: [],
  research_readiness: { status: 'ready', reasons: [], financial_staleness_days: 30, financial_period_end: '2026-03-31', insider_evidence_status: 'covered_transactions' },
  research_next_step: { status: 'ready', priority: 'normal', action: '阅读近期 SEC 文件并设定研究论点', rationale: '关键研究证据已完整。', reasons: [] },
  technical: { status: 'data_insufficient', sample_days: 7, required_sample_days: 21, trade_date: '2026-06-30', close_usd: 12.3, ma20_usd: 0, ma50_usd: 0, ma200_usd: 0, ma200_available: false, prior_close_usd: 0, prior_ma20_usd: 0, distance_to_ma20_pct: 0, prior_20d_high_usd: 0, distance_to_20d_high_pct: 0, average_volume_20: 0, volume_ratio_20: 0, dollar_volume_usd: 0, average_dollar_volume_20: 0, dollar_volume_ratio_20: 0, liquidity_status: 'unknown', high_50d_usd: 0, distance_to_50d_high_pct: 0, high_200d_usd: 0, distance_to_200d_high_pct: 0, relative_strength: { status: 'missing', benchmark_ticker: 'IWM', matched_sample_days: 0 }, anchored_vwap: { status: 'anchor_unavailable', anchor_event_type: '', anchor_label: '', anchor_trade_date: '', price_trade_date: '', trading_days: 0, approximate_vwap_usd: 0, distance_pct: 0, price_source: '' }, oscillator: { status: 'data_insufficient', kdj_method: 'close_range_9_3_3', signal: 'unavailable', label: '历史不足', reasons: [] }, signals: [], trade_setup: { status: 'unavailable', bias: 'neutral', entry_trigger: '', stop_loss_usd: 0, risk_pct: 0, take_profit_zone_low_usd: 0, take_profit_zone_high_usd: 0, exit_reason: '', reasons: ['日线历史不足，暂不生成交易计划'] } },
	technical_history: [],
  data_quality: { financial: 'valid' },
  data_lineage: {
    score_batch_id: 'batch',
    evidence_batch_id: 'security-batch',
    batch_effective_date: '2026-06-30',
    items: [{ key: 'financial', label: '财务指标', source: 'SEC Company Facts → 本地财务指标快照', as_of: '2026-06-30', status: 'valid', detail: '测试快照' }],
  },
  evidence: [{ field: 'total_score', value: '88', source: 'candidate_score_snapshots' }],
  recent_filings: [],
}

export const candidateHealthTypecheck: CandidateHealth = {
  batch_id: 'batch',
  status: 'ok',
  total_candidates: 1,
  missing_financials: 0,
  missing_insiders: 0,
  insider_data_status: 'available',
  insider_lineage_status: 'source_version',
  candidates_with_insider_records: 1,
  insider_record_coverage_pct: 100,
  qualified_insider_candidates: 1,
  no_qualified_insider_candidates: 0,
  candidates_with_recent_filings: 1,
  recent_filing_coverage_pct: 100,
  price_effective_date: '2026-06-30',
  current_price_candidates: 1,
  fallback_price_candidates: 0,
  stale_price_candidates: 0,
  missing_price_candidates: 0,
  missing_market_cap: 0,
  active_risk_events: 0,
  issues: [],
}

export const discoveryWorkflowTypecheck: DiscoveryWorkflowResult = {
  status: 'published',
  batch_id: 'batch',
  summary: candidateSummaryTypecheck,
  health: candidateHealthTypecheck,
}

export const candidateReportTypecheck: CandidateReport = {
	status: 'ready',
	available: true,
  date: '2026-06-30',
  batch: {
    batch_id: 'batch',
    kind: 'market-prescreen',
    status: 'published',
    effective_date: '2026-06-30',
    record_count: 1,
    started_at: '2026-06-30T00:00:00Z',
    error_message: '',
  },
  summary: candidateSummaryTypecheck,
  health: candidateHealthTypecheck,
	snapshot_id: 1,
	schema_version: 'candidate-report-v1',
	content_sha256: 'abc123',
  generated_at: '2026-06-30T00:00:00Z',
}
